'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import AppShell from '../../components/AppShell';
import { apiRequest } from '../../lib/api';

type Dashboard = { summary: Record<string, number>; recentIncidents: { id: string; title: string; status: string; severity: string; detectedAt: string; service: { name: string }; serviceEnvironment: { name: string } }[]; recentEvents: { id: string; type: string; message: string; timestamp: string; service: { name: string } }[]; serviceHealth: { id: string; name: string; environments: { id: string; name: string; _count: { events: number; incidents: number }; incidents: { id: string; title: string; severity: string }[] }[] }[] };

export default function DashboardPage() {
  const [data, setData] = useState<Dashboard | null>(null);
  const [error, setError] = useState('');
  useEffect(() => { const load = () => void apiRequest<Dashboard>('/dashboard/summary').then(setData).catch((requestError: unknown) => setError(requestError instanceof Error ? requestError.message : 'Unable to load dashboard')); load(); const timer = window.setInterval(load, 60000); return () => window.clearInterval(timer); }, []);
  return <AppShell title="Dashboard" eyebrow="Operational overview"><section className="metric-grid">{data ? Object.entries(data.summary).map(([label, value]) => <article className="metric" key={label}><span>{label.replace(/[A-Z]/g, (letter) => ` ${letter}`).replace(/^./, (letter) => letter.toUpperCase())}</span><strong>{value}</strong></article>) : <div className="panel">{error || 'Loading dashboard...'}</div>}</section><div className="dashboard-grid"><section className="panel"><div className="section-heading"><div><p className="eyebrow">Live queue</p><h2>Recent incidents</h2></div><Link href="/incidents" className="text-button">View all</Link></div>{data?.recentIncidents.length ? <div className="table-wrap"><table><thead><tr><th>Incident</th><th>Severity</th><th>Status</th><th>Detected</th></tr></thead><tbody>{data.recentIncidents.map((incident) => <tr key={incident.id}><td><Link href={`/incident/${incident.id}`} className="row-title">{incident.title}</Link><small>{incident.service.name} · {incident.serviceEnvironment.name}</small></td><td><span className={`severity severity-${incident.severity.toLowerCase()}`}>{incident.severity}</span></td><td>{incident.status}</td><td>{new Date(incident.detectedAt).toLocaleString()}</td></tr>)}</tbody></table></div> : <div className="empty">{error || 'No incident activity yet.'}</div>}</section><section className="panel"><div className="section-heading"><div><p className="eyebrow">Telemetry</p><h2>Recent events</h2></div></div>{data?.recentEvents.length ? <div className="event-list">{data.recentEvents.map((event) => <div className="event-item" key={event.id}><span className="event-type">{event.type}</span><div><strong>{event.message}</strong><small>{event.service.name} · {new Date(event.timestamp).toLocaleString()}</small></div></div>)}</div> : <div className="empty">No telemetry received yet.</div>}</section></div>{data && <section className="panel"><div className="section-heading"><div><p className="eyebrow">Coverage</p><h2>Service health</h2></div></div>{data.serviceHealth.length ? <div className="event-list">{data.serviceHealth.flatMap((service) => service.environments.map((environment) => <div className="event-item" key={environment.id}><span className="event-type">{environment.incidents.length ? 'ACTIVE' : 'HEALTHY'}</span><div><strong>{service.name} · {environment.name}</strong><small>{environment._count.events} events · {environment._count.incidents} incidents</small></div></div>))}</div> : <div className="empty">No services configured yet.</div>}</section>}</AppShell>;
}
