import { Router } from 'express';
import { requireAuth } from '../middleware/auth';
import { requirePrimaryOrganizationMembership, requireRole } from '../middleware/organization';
import { asyncHandler } from '../utils/asyncHandler';
import { analyzeIncidentRootCause, askIncidentCopilot, generateIncidentPostmortem, getIncident, getIncidentCopilot, getIncidentPostmortem, getIncidentRootCause, listIncidentDeployments, listIncidentEvents, listIncidents, updateIncident } from '../controllers/incidentController';

const router = Router();
router.use(requireAuth);
router.get('/', asyncHandler(listIncidents));
router.get('/:incidentId', asyncHandler(getIncident));
router.get('/:incidentId/events', asyncHandler(listIncidentEvents));
router.get('/:incidentId/deployments', asyncHandler(listIncidentDeployments));
router.get('/:incidentId/ai/root-cause', asyncHandler(getIncidentRootCause));
router.get('/:incidentId/ai/copilot', requirePrimaryOrganizationMembership, requireRole('MEMBER'), asyncHandler(getIncidentCopilot));
router.post('/:incidentId/ai/root-cause', requirePrimaryOrganizationMembership, requireRole('MEMBER'), asyncHandler(analyzeIncidentRootCause));
router.post('/:incidentId/ai/copilot', requirePrimaryOrganizationMembership, requireRole('MEMBER'), asyncHandler(askIncidentCopilot));
router.get('/:incidentId/ai/postmortem', asyncHandler(getIncidentPostmortem));
router.post('/:incidentId/ai/postmortem', requirePrimaryOrganizationMembership, requireRole('MEMBER'), asyncHandler(generateIncidentPostmortem));
router.patch('/:incidentId', requirePrimaryOrganizationMembership, requireRole('MEMBER'), asyncHandler(updateIncident));
export default router;